### ISSUE TITLE
Add random suffix if none is provided

### ISSUE THREAD

**Issue by AlexanderBrevig** [entur/terraform#12]
Ability to ignore `*suffix `variables and have TF generate a random blurb for you.

This will make segmented environments easier as they do not need to overwrite a new suffix per env. Additionally it makes destroy and apply more convenient as you will not get a naming collision for a postgres f.ex.

**Comment by sindrel** [comment]
Pull request: #13

**Comment by sindrel** [comment]
Random suffix support has been added to postgres module in #13.
