### ISSUE TITLE
Support Bring-Your-Own-Service-Account

### ISSUE THREAD

**Issue by Spikra** [entur/terraform#23]
Currently every module creates it's own service account, while in some cases might be preferable to use a common service to access all GCP services from the application. 
The service account email should also be present in outputs to make it available to the terraform code using the modules.

**Comment by sindrel** [comment]
See #25

**Comment by AlexanderBrevig** [comment]
Resolved by #25

**Comment by AlexanderBrevig** [comment]
my bad
