### ISSUE TITLE
Change bucket policy to avoid deprecation warning

### ISSUE THREAD

**Issue by Chr1stian** [entur/terraform#51]
```
Warning: Attribute is deprecated

  on .terraform/modules/bucket/modules/bucket/main.tf line 16, in resource "google_storage_bucket" "storage_bucket":
  16:   bucket_policy_only = var.bucket_policy_only

Please use the uniform_bucket_level_access as this field has been renamed by
Google.

```

**Comment by dpkirchner** [comment]
Note: You may still see this error even when you're using `uniform_bucket_level_access`. If so your only choice (that I can tell) is to perform surgery on your state file, replacing the `bucket_policy_only` variable there. (Don't forget to bump the serial number before pushing state back to storage.)
